author: Pablo Bollansée

# Info Links
website_hr: www.PabloProductions.be
website: https://www.pabloproductions.be/

# Collections
collections:
  slides:
    output: false
  css:
    output: false
  projects:
    output: false

# Defaults
permalink: pretty
