author: Pablo Bollansée

# Info Links
public_email: Pablo.Bollansee@gmail.com

website_hr: www.PabloProductions.be
website: https://www.pabloproductions.be/

# Download links
reconnect_dl_latest: https://www.dropbox.com/s/4s96v6oxjf6glhx/ReConnect-Installer.rar?dl=0

# Collections
collections:
  slides:
    output: false
  css:
    output: false
  projects:
    output: false

# Defaults
permalink: pretty
