author: Pablo Bollansée

# Info Links
public_email: Pablo.Bollansee@gmail.com

website_hr: PabloProductions.be
website: https://www.pabloproductions.be/

github_name: TheOddler
github_link_hr: Github.com/TheOddler
github_link: https://github.com/TheOddler/

bitbucket_name: TheOddler
bitbucket_link_hr: Bitbucket.org/TheOddler
bitbucket_link: https://bitbucket.org/TheOddler/

# Unity Links
masterwars_unity: //dl.dropboxusercontent.com/u/10448192/Master%20Wars%20Ball/Master%20Wars%20Ball.unity3d

# Download links
reconnect_dl_latest: https://www.dropbox.com/s/4s96v6oxjf6glhx/ReConnect-Installer.rar?dl=0

collections:
  slides:
    output: false
  css:
    output: false
